services:  
  pokedex:
    image: pokedex
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - 8080:8080
